language: php

sudo: false

php:
  - 7

matrix:
  fast_finish: true

addons:
  sauce_connect: true
  hosts:
  - mysite.dev
  - www.mysite.dev

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - export PATH=./bin/:$PATH
  - export SAUCE_BUILD=$TRAVIS_BUILD_NUMBER
  - export SAUCE_TUNNEL_IDENTIFIER=$TRAVIS_JOB_NUMBER
  - php -S localhost:8888 &
  - sleep 3

script:
  - phing coverage

after_script:
  - php ./bin/coveralls -v