language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

addons:
  sauce_connect: true

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - export PATH=./bin/:$PATH

script:
  - phing coverage

after_script:
  - php ./bin/coveralls -v